name: Packaging

on:
  - push

jobs:
  setup-python:
    name: Setup Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@2
        with:
          python-version: "3.10"

      - run: |
          python -m pip install tox
          tox -e format

