name: Packaging

on:
  - push

jobs:
  check-format:
    name: Run formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: |
          python -m pip install tox
          tox -e format

  check-lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: |
          python -m pip install tox
          tox -e lint

  check-typing:
    name: Run typechecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: |
          python -m pip install tox
          tox -e typecheck
